// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: gen/proto/iam/v1/token_validation.proto

package iamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenValidationService_Validate_FullMethodName = "/iam.v1.TokenValidationService/Validate"
)

// TokenValidationServiceClient is the client API for TokenValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenValidationServiceClient interface {
	Validate(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type tokenValidationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenValidationServiceClient(cc grpc.ClientConnInterface) TokenValidationServiceClient {
	return &tokenValidationServiceClient{cc}
}

func (c *tokenValidationServiceClient) Validate(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, TokenValidationService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenValidationServiceServer is the server API for TokenValidationService service.
// All implementations must embed UnimplementedTokenValidationServiceServer
// for forward compatibility.
type TokenValidationServiceServer interface {
	Validate(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	mustEmbedUnimplementedTokenValidationServiceServer()
}

// UnimplementedTokenValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenValidationServiceServer struct{}

func (UnimplementedTokenValidationServiceServer) Validate(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedTokenValidationServiceServer) mustEmbedUnimplementedTokenValidationServiceServer() {
}
func (UnimplementedTokenValidationServiceServer) testEmbeddedByValue() {}

// UnsafeTokenValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenValidationServiceServer will
// result in compilation errors.
type UnsafeTokenValidationServiceServer interface {
	mustEmbedUnimplementedTokenValidationServiceServer()
}

func RegisterTokenValidationServiceServer(s grpc.ServiceRegistrar, srv TokenValidationServiceServer) {
	// If the following call pancis, it indicates UnimplementedTokenValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenValidationService_ServiceDesc, srv)
}

func _TokenValidationService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenValidationServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenValidationService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenValidationServiceServer).Validate(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenValidationService_ServiceDesc is the grpc.ServiceDesc for TokenValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.v1.TokenValidationService",
	HandlerType: (*TokenValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _TokenValidationService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gen/proto/iam/v1/token_validation.proto",
}
