// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: gen/proto/iam/v1/token.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidateTokenRequest contains the token to validate.
type ValidateTokenRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpectedAudience []string               `protobuf:"bytes,2,rep,name=expected_audience,json=expectedAudience,proto3" json:"expected_audience,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTokenRequest) GetExpectedAudience() []string {
	if x != nil {
		return x.ExpectedAudience
	}
	return nil
}

// ValidateTokenResponse contains validation result metadata.
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Jti           string                 `protobuf:"bytes,6,opt,name=jti,proto3" json:"jti,omitempty"`
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ValidateTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ValidateTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidateTokenResponse) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *ValidateTokenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// IntrospectRequest requests detailed token status.
type IntrospectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Token           string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CheckRevocation *bool                  `protobuf:"varint,2,opt,name=check_revocation,json=checkRevocation,proto3,oneof" json:"check_revocation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IntrospectRequest) Reset() {
	*x = IntrospectRequest{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectRequest) ProtoMessage() {}

func (x *IntrospectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectRequest.ProtoReflect.Descriptor instead.
func (*IntrospectRequest) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{2}
}

func (x *IntrospectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IntrospectRequest) GetCheckRevocation() bool {
	if x != nil && x.CheckRevocation != nil {
		return *x.CheckRevocation
	}
	return false
}

// IntrospectResponse contains detailed token information.
type IntrospectResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Active           bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username         string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Roles            []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	IssuedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	NotBefore        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	Jti              string                 `protobuf:"bytes,8,opt,name=jti,proto3" json:"jti,omitempty"`
	SessionId        string                 `protobuf:"bytes,9,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Revoked          bool                   `protobuf:"varint,10,opt,name=revoked,proto3" json:"revoked,omitempty"`
	RevocationReason string                 `protobuf:"bytes,11,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"`
	Session          *SessionInfo           `protobuf:"bytes,12,opt,name=session,proto3" json:"session,omitempty"`
	Error            string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IntrospectResponse) Reset() {
	*x = IntrospectResponse{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectResponse) ProtoMessage() {}

func (x *IntrospectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectResponse.ProtoReflect.Descriptor instead.
func (*IntrospectResponse) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{3}
}

func (x *IntrospectResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *IntrospectResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IntrospectResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *IntrospectResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *IntrospectResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *IntrospectResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *IntrospectResponse) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *IntrospectResponse) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *IntrospectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IntrospectResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *IntrospectResponse) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

func (x *IntrospectResponse) GetSession() *SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *IntrospectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SessionInfo captures session details relevant for introspection results.
type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceLabel   string                 `protobuf:"bytes,2,opt,name=device_label,json=deviceLabel,proto3" json:"device_label,omitempty"`
	IpLast        string                 `protobuf:"bytes,3,opt,name=ip_last,json=ipLast,proto3" json:"ip_last,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Revoked       bool                   `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{4}
}

func (x *SessionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionInfo) GetDeviceLabel() string {
	if x != nil {
		return x.DeviceLabel
	}
	return ""
}

func (x *SessionInfo) GetIpLast() string {
	if x != nil {
		return x.IpLast
	}
	return ""
}

func (x *SessionInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *SessionInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SessionInfo) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

// RevokeByJTIRequest revokes a token by JWT ID.
type RevokeByJTIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jti           string                 `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeByJTIRequest) Reset() {
	*x = RevokeByJTIRequest{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeByJTIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeByJTIRequest) ProtoMessage() {}

func (x *RevokeByJTIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeByJTIRequest.ProtoReflect.Descriptor instead.
func (*RevokeByJTIRequest) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeByJTIRequest) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *RevokeByJTIRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RevokeBySessionRequest revokes tokens bound to a session.
type RevokeBySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeBySessionRequest) Reset() {
	*x = RevokeBySessionRequest{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeBySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeBySessionRequest) ProtoMessage() {}

func (x *RevokeBySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeBySessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeBySessionRequest) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeBySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RevokeBySessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RevokeAllForUserRequest revokes all tokens for a user.
type RevokeAllForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAllForUserRequest) Reset() {
	*x = RevokeAllForUserRequest{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllForUserRequest) ProtoMessage() {}

func (x *RevokeAllForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllForUserRequest.ProtoReflect.Descriptor instead.
func (*RevokeAllForUserRequest) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeAllForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeAllForUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RevokeResponse conveys revocation outcome.
type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RevokedCount  int32                  `protobuf:"varint,2,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeResponse) GetRevokedCount() int32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

func (x *RevokeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_gen_proto_iam_v1_token_proto protoreflect.FileDescriptor

const file_gen_proto_iam_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x1cgen/proto/iam/v1/token.proto\x12\x06iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12+\n" +
	"\x11expected_audience\x18\x02 \x03(\tR\x10expectedAudience\"\xde\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x10\n" +
	"\x03jti\x18\x06 \x01(\tR\x03jti\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"n\n" +
	"\x11IntrospectRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12.\n" +
	"\x10check_revocation\x18\x02 \x01(\bH\x00R\x0fcheckRevocation\x88\x01\x01B\x13\n" +
	"\x11_check_revocation\"\xe3\x03\n" +
	"\x12IntrospectResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"not_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x12\x10\n" +
	"\x03jti\x18\b \x01(\tR\x03jti\x12\x1d\n" +
	"\n" +
	"session_id\x18\t \x01(\tR\tsessionId\x12\x18\n" +
	"\arevoked\x18\n" +
	" \x01(\bR\arevoked\x12+\n" +
	"\x11revocation_reason\x18\v \x01(\tR\x10revocationReason\x12-\n" +
	"\asession\x18\f \x01(\v2\x13.iam.v1.SessionInfoR\asession\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\"\xe7\x01\n" +
	"\vSessionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdevice_label\x18\x02 \x01(\tR\vdeviceLabel\x12\x17\n" +
	"\aip_last\x18\x03 \x01(\tR\x06ipLast\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\arevoked\x18\x06 \x01(\bR\arevoked\">\n" +
	"\x12RevokeByJTIRequest\x12\x10\n" +
	"\x03jti\x18\x01 \x01(\tR\x03jti\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"O\n" +
	"\x16RevokeBySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"J\n" +
	"\x17RevokeAllForUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"e\n" +
	"\x0eRevokeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rrevoked_count\x18\x02 \x01(\x05R\frevokedCount\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xfc\x02\n" +
	"\fTokenService\x12L\n" +
	"\rValidateToken\x12\x1c.iam.v1.ValidateTokenRequest\x1a\x1d.iam.v1.ValidateTokenResponse\x12C\n" +
	"\n" +
	"Introspect\x12\x19.iam.v1.IntrospectRequest\x1a\x1a.iam.v1.IntrospectResponse\x12A\n" +
	"\vRevokeByJTI\x12\x1a.iam.v1.RevokeByJTIRequest\x1a\x16.iam.v1.RevokeResponse\x12I\n" +
	"\x0fRevokeBySession\x12\x1e.iam.v1.RevokeBySessionRequest\x1a\x16.iam.v1.RevokeResponse\x12K\n" +
	"\x10RevokeAllForUser\x12\x1f.iam.v1.RevokeAllForUserRequest\x1a\x16.iam.v1.RevokeResponseBKZIgithub.com/arklim/social-platform-iam/internal/transport/grpc/iamv1;iamv1b\x06proto3"

var (
	file_gen_proto_iam_v1_token_proto_rawDescOnce sync.Once
	file_gen_proto_iam_v1_token_proto_rawDescData []byte
)

func file_gen_proto_iam_v1_token_proto_rawDescGZIP() []byte {
	file_gen_proto_iam_v1_token_proto_rawDescOnce.Do(func() {
		file_gen_proto_iam_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gen_proto_iam_v1_token_proto_rawDesc), len(file_gen_proto_iam_v1_token_proto_rawDesc)))
	})
	return file_gen_proto_iam_v1_token_proto_rawDescData
}

var file_gen_proto_iam_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gen_proto_iam_v1_token_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),    // 0: iam.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),   // 1: iam.v1.ValidateTokenResponse
	(*IntrospectRequest)(nil),       // 2: iam.v1.IntrospectRequest
	(*IntrospectResponse)(nil),      // 3: iam.v1.IntrospectResponse
	(*SessionInfo)(nil),             // 4: iam.v1.SessionInfo
	(*RevokeByJTIRequest)(nil),      // 5: iam.v1.RevokeByJTIRequest
	(*RevokeBySessionRequest)(nil),  // 6: iam.v1.RevokeBySessionRequest
	(*RevokeAllForUserRequest)(nil), // 7: iam.v1.RevokeAllForUserRequest
	(*RevokeResponse)(nil),          // 8: iam.v1.RevokeResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_gen_proto_iam_v1_token_proto_depIdxs = []int32{
	9,  // 0: iam.v1.ValidateTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 1: iam.v1.IntrospectResponse.issued_at:type_name -> google.protobuf.Timestamp
	9,  // 2: iam.v1.IntrospectResponse.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 3: iam.v1.IntrospectResponse.not_before:type_name -> google.protobuf.Timestamp
	4,  // 4: iam.v1.IntrospectResponse.session:type_name -> iam.v1.SessionInfo
	9,  // 5: iam.v1.SessionInfo.last_seen:type_name -> google.protobuf.Timestamp
	9,  // 6: iam.v1.SessionInfo.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 7: iam.v1.TokenService.ValidateToken:input_type -> iam.v1.ValidateTokenRequest
	2,  // 8: iam.v1.TokenService.Introspect:input_type -> iam.v1.IntrospectRequest
	5,  // 9: iam.v1.TokenService.RevokeByJTI:input_type -> iam.v1.RevokeByJTIRequest
	6,  // 10: iam.v1.TokenService.RevokeBySession:input_type -> iam.v1.RevokeBySessionRequest
	7,  // 11: iam.v1.TokenService.RevokeAllForUser:input_type -> iam.v1.RevokeAllForUserRequest
	1,  // 12: iam.v1.TokenService.ValidateToken:output_type -> iam.v1.ValidateTokenResponse
	3,  // 13: iam.v1.TokenService.Introspect:output_type -> iam.v1.IntrospectResponse
	8,  // 14: iam.v1.TokenService.RevokeByJTI:output_type -> iam.v1.RevokeResponse
	8,  // 15: iam.v1.TokenService.RevokeBySession:output_type -> iam.v1.RevokeResponse
	8,  // 16: iam.v1.TokenService.RevokeAllForUser:output_type -> iam.v1.RevokeResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_gen_proto_iam_v1_token_proto_init() }
func file_gen_proto_iam_v1_token_proto_init() {
	if File_gen_proto_iam_v1_token_proto != nil {
		return
	}
	file_gen_proto_iam_v1_token_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gen_proto_iam_v1_token_proto_rawDesc), len(file_gen_proto_iam_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gen_proto_iam_v1_token_proto_goTypes,
		DependencyIndexes: file_gen_proto_iam_v1_token_proto_depIdxs,
		MessageInfos:      file_gen_proto_iam_v1_token_proto_msgTypes,
	}.Build()
	File_gen_proto_iam_v1_token_proto = out.File
	file_gen_proto_iam_v1_token_proto_goTypes = nil
	file_gen_proto_iam_v1_token_proto_depIdxs = nil
}
