// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: gen/proto/iam/v1/token.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetJWKSRequest is empty - no parameters needed.
type GetJWKSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWKSRequest) Reset() {
	*x = GetJWKSRequest{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWKSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWKSRequest) ProtoMessage() {}

func (x *GetJWKSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWKSRequest.ProtoReflect.Descriptor instead.
func (*GetJWKSRequest) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{0}
}

// GetJWKSResponse contains the JSON Web Key Set.
type GetJWKSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwksJson      string                 `protobuf:"bytes,1,opt,name=jwks_json,json=jwksJson,proto3" json:"jwks_json,omitempty"` // Raw JSON containing the JWKS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWKSResponse) Reset() {
	*x = GetJWKSResponse{}
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWKSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWKSResponse) ProtoMessage() {}

func (x *GetJWKSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_iam_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWKSResponse.ProtoReflect.Descriptor instead.
func (*GetJWKSResponse) Descriptor() ([]byte, []int) {
	return file_gen_proto_iam_v1_token_proto_rawDescGZIP(), []int{1}
}

func (x *GetJWKSResponse) GetJwksJson() string {
	if x != nil {
		return x.JwksJson
	}
	return ""
}

var File_gen_proto_iam_v1_token_proto protoreflect.FileDescriptor

const file_gen_proto_iam_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x1cgen/proto/iam/v1/token.proto\x12\x06iam.v1\"\x10\n" +
	"\x0eGetJWKSRequest\".\n" +
	"\x0fGetJWKSResponse\x12\x1b\n" +
	"\tjwks_json\x18\x01 \x01(\tR\bjwksJson2J\n" +
	"\fTokenService\x12:\n" +
	"\aGetJWKS\x12\x16.iam.v1.GetJWKSRequest\x1a\x17.iam.v1.GetJWKSResponseBKZIgithub.com/arklim/social-platform-iam/internal/transport/grpc/iamv1;iamv1b\x06proto3"

var (
	file_gen_proto_iam_v1_token_proto_rawDescOnce sync.Once
	file_gen_proto_iam_v1_token_proto_rawDescData []byte
)

func file_gen_proto_iam_v1_token_proto_rawDescGZIP() []byte {
	file_gen_proto_iam_v1_token_proto_rawDescOnce.Do(func() {
		file_gen_proto_iam_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gen_proto_iam_v1_token_proto_rawDesc), len(file_gen_proto_iam_v1_token_proto_rawDesc)))
	})
	return file_gen_proto_iam_v1_token_proto_rawDescData
}

var file_gen_proto_iam_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gen_proto_iam_v1_token_proto_goTypes = []any{
	(*GetJWKSRequest)(nil),  // 0: iam.v1.GetJWKSRequest
	(*GetJWKSResponse)(nil), // 1: iam.v1.GetJWKSResponse
}
var file_gen_proto_iam_v1_token_proto_depIdxs = []int32{
	0, // 0: iam.v1.TokenService.GetJWKS:input_type -> iam.v1.GetJWKSRequest
	1, // 1: iam.v1.TokenService.GetJWKS:output_type -> iam.v1.GetJWKSResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gen_proto_iam_v1_token_proto_init() }
func file_gen_proto_iam_v1_token_proto_init() {
	if File_gen_proto_iam_v1_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gen_proto_iam_v1_token_proto_rawDesc), len(file_gen_proto_iam_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gen_proto_iam_v1_token_proto_goTypes,
		DependencyIndexes: file_gen_proto_iam_v1_token_proto_depIdxs,
		MessageInfos:      file_gen_proto_iam_v1_token_proto_msgTypes,
	}.Build()
	File_gen_proto_iam_v1_token_proto = out.File
	file_gen_proto_iam_v1_token_proto_goTypes = nil
	file_gen_proto_iam_v1_token_proto_depIdxs = nil
}
